### PR TITLE
Appendix

### PR DESCRIPTION
**Pull request by Nautman**
Implemented ability to upload appendices.

### CODE REVIEW

**Comment by Zigolox** [comment]
Will leave this here:

* Cog bar is some pixels bigger than other bar and color is image
* Whenever a file is uploaded a .pdf is unnecessary added to the end when downloading
* When deleting a file the progress bar should decrease
* Pressing the cog menu also highlights its border blue like selecting text. This is also a problem with uploading a file for the first time. Whole bar should be highlighted or not at all

**Comment by Nautman** [comment]
Completed form now has a green hue btw.

**Comment by Nautman** [comment]
Please review if this is ready to be merged @Zigolox! :)

**Comment by Nautman** [comment]
This isn't ready to be merged. I found a bug when you are logged out. Will update you when it is fixed.

**Comment by Nautman** [comment]
I fixed the bug. Do you think this is ready to be merged @Zigolox?

**Comment by Zigolox** [comment]
Yes, appendix are however still getting an error when uploading a file that is >5mb but the file is still uploaded. When this i fixed I can do a code review

**Comment by Nautman** [comment]
Fixed @Zigolox. When you merge this, please do *not* do a squash merge.

**Comment by Zigolox** [comment]
There is still the ".pdf.pdf"-error in the appendix section

**Comment by Nautman** [comment]
Pushed changes. Could you please review that it works now? @Zigolox

**Review by Zigolox — APPROVED** [review]
Looks good, well done @Nautman!

**Pull request merged**
