### PR TITLE
Admin

### PR DESCRIPTION
**Pull request by Nautman**
This PR will add admin features to the portal

### CODE REVIEW

**Comment by Zigolox** [comment]
image
* Bold face and lines between the sections.
* Aligne the window to the middle of the screen 
image
* The site cannot be aligned to the middle. Whenever another tab is checked the menu moved depending on how much content is on the screen. 
image
image
* The person should turn green if they are fully reviewed.
* More space between button and table 
image
* Remove the top list since this can influence results.

**Comment by Nautman** [comment]
When should the top list be added?

**Comment by Zigolox** [comment]
Probably then everyone have finished reviewing. It could however be interesting to see how many have reviewed a person.

**Comment by Zigolox** [comment]
Will my issues be fixed?

**Comment by Nautman** [comment]
I will fix (at least most of) your issues but it might take a couple of days.

**Comment by Nautman** [comment]
> Bold face and lines between the sections.

Done

> Aligne the window to the middle of the screen

Will have to wait. I'm not entirely sure if this looks good or how to even implement it nicely.

> The site cannot be aligned to the middle. Whenever another tab is checked the menu moved depending on how much content is on the screen.

I don't understand what you mean. Could you please elaborate?

> The person should turn green if they are fully reviewed.

Unfortunately, I don't have the ability of checking if someone is reviewed. To do this an [issue has to be resolved in infrarays-api](https://github.com/digitalungdom-se/infrarays-api/issues/15) first.

> More space between button and table

Done.

> Remove the top list since this can influence results.

I don't know how to handle this. I think it's not a very good idea to remove it and then have the reviewers ask us to open it once they want to see it. Do you think perhaps we could put a banner or a button that would reveal the top list?

**Comment by Zigolox** [comment]
- When hovering over a star "Layer 1" sometimes appear

image
- Why can't we just randomize the first time they log-in? 

image
- English translation

image
image
image
image

- Why should normal admins be allowed to see who other admins are?

- "Visa" is a bad name for the application. "Ansökning" or just "PDF" works better
image

> I don't understand what you mean. Could you please elaborate?
- We will have to have a voice chat about this!

**Comment by Zigolox** [comment]
The current menu for showing what individual people have graded is currently unusable. It would be better if it worked like the application portals survey which scrolls down smoothly. I also think we once again have a problem with the frame being centred.

**Comment by Zigolox** [comment]
There are still some issues that needs to be resolved but it looks a lot better and I will merge!

**Review by Zigolox — APPROVED** [review]

**Pull request merged**
