### PR TITLE
TypeScript partial rewrite & ability to copy login code

### PR DESCRIPTION
**Pull request by Nautman**
This PR rewrites some parts to TypeScript and also adds a neat function to copy the login code to your clipboard. This will help people who want to try the portal without opening developer console! This is what it looks like:
image

### CODE REVIEW

**Comment by Zigolox** [comment]
Seems like a great feature! Why isn't it building @Nautman?

**Comment by Nautman** [comment]
It was not building because there were some references to files that I deleted. It's worth noting that these changes relies upon an admin fix being merged (such as the open PR #37).

**Comment by Nautman** [comment]
This PR has some "hard-coded" values, which relies upon our dev-server being used. As such, if you were to wish that it connects to another server it will not show the value. It does

```js
if(res.data && res.config.baseUrl === "https://devapi.infrarays.digitalungdom.se") {
// show
}
```

Perhaps it would only necessary to do this, but then one has to assume that the API doesn't start to send any result before a fix has been merged to the front-end.
```js

if(res.data) {
// show
}
```

**Comment by Nautman** [comment]
Note that it also gives a notification for letters of recommendation.
image

**Comment by Zigolox** [comment]
It is important to note that we shouldn't add no many features to the dev-api since this can make it harder to see problems in the real one. These you made is however necessary to ease the usage since we aren't using mail.

**Comment by Nautman** [comment]
Do you think you could review this @Zigolox?

**Comment by Zigolox** [comment]
Yes, but don't the admin PR need to be merged first?

**Comment by Nautman** [comment]
No it doesn't have to be merged first. This PR breaks the admin page (that is already broken), but these breaks will be fixed by the other PR.

**Comment by Zigolox** [comment]
Ok everything seem good. The only thing I found was that the copied message should be removed after some time and that it should be translate into english. 
image

**Comment by Nautman** [comment]
Fixed @Zigolox.

**Comment by Nautman** [comment]
Do you think it is ready to be merged? @Zigolox

**Comment by Zigolox** [comment]
We're now using two different notification methods. I also think the log-in notification should use be up until the user successfully log in. 
image
image

**Comment by Nautman** [comment]
It is very hard for me to make sure that the "copied" notification stays up until the user is logged in. I also think that's not very logical.

I gave the logout notification a blank background.

**Comment by Zigolox** [comment]
Okay, I however think it's not on theme to have a rainbow progress bar. The rays colour might be more appropriate.

**Comment by Nautman** [comment]
It is now the rays colour.

**Comment by Zigolox** [comment]
Great! This however introduced a bug where the logged out text has lower contrast. 
image

**Comment by Nautman** [comment]
I'll fix that.

**Comment by Nautman** [comment]
I've pushed a fix @Zigolox.

**Comment by Zigolox** [comment]
Looks, good now. Will merge this

**Comment by Nautman** [comment]
Great, thank you!

**Pull request merged**
