### PR TITLE
Download delete file

### PR DESCRIPTION
**Pull request by Nautman**
This is a feature to download or delete individual files

### CODE REVIEW

**Comment by Nautman** [comment]
This probably needs fix for #32 before merging.

**Comment by Nautman** [comment]
This is ready to be reviewed. It adds the ability to download and delete a file. Could you test this when you have time @Zigolox?

**Comment by Nautman** [comment]
Perhaps the text for download / downloading, delete / deleting, cancel needs to be translated. This is a reminder for myself to check this.

**Comment by Zigolox** [comment]
* Cog bar is some pixels bigger than other bar image
* Whenever a file is uploaded a .pdf is unnecessary added to the end when downloading
* When deleting a file the bar should turn white and the progress bar should decreese

**Comment by Nautman** [comment]
Thank you so much for your review @Zigolox!

> Whenever a file is uploaded a .pdf is unnecessary added to the end when downloading
I can't reproduce this?

> When deleting a file the bar should turn white
Fixed in #34 

> Pressing the cog menu also highlights its border blue like selecting text
I can't reproduce this

The rest of the issues you mentioned will be fixed in #34 and I will therefore close this pull request since it is unnecessary to fix things in this PR that have already been fixed in the new PR.

**Pull request closed without merging**
