### PR TITLE
Added developed by Digital Ungdom on every page

### PR DESCRIPTION
**Pull request by Nautman**
https://youtu.be/CYTigFnZggc?t=144

### CODE REVIEW

**Comment by Zigolox** [comment]
Haha, best PR-comment I've ever read. 

I however wonder if it's better to do it at the absolute bottom or if that would look weird.

It also seems like the design has become much thinner. Is this related to this change?

**Comment by Nautman** [comment]
It is mentioned at the absolute bottom now.

And yes, it was a bug that the design had become much thinner. It had actually become unusable if you were logged in because you could not scroll. It was good that you caught that error!

**Comment by Nautman** [comment]
It turns out this version has bugs in Firefox as things aren't centered. This isn't ready to be merged.

**Comment by Zigolox** [comment]
Good catch! Will review when finished. ;)

**Comment by Nautman** [comment]
This is ready to be reviewed and merged.

**Comment by Zigolox** [comment]
Looks good, will everyone get logged out if I merge this?

**Comment by Nautman** [comment]
They will not be logged out.

**Pull request merged**
