### PR TITLE
Ability to see applicant information

### PR DESCRIPTION
**Pull request by Nautman**
This helps the grading team know more information about the applicant without opening the PDF.

### CODE REVIEW

**Comment by Zigolox** [comment]
Should we only have the email address there and not more information?

**Comment by Nautman** [comment]
What more information would you like?

**Comment by Nautman** [comment]
I've fixed your issues except

> If all files are deleted a randomization is needed.

Because I don't understand what you mean?

**Comment by Nautman** [comment]
Turns out that the visual regression testing has found a bug with the borders that I might want to check out. However, the visual bug is found nowhere in the application since the component is not used in that manner. Shortly said: there is a visual bug but it only exists in theory.

**Comment by Nautman** [comment]
If this is merged relatively soon we will easily be able to see what parts of a persons application has errors :)

**Comment by Zigolox** [comment]
> I've fixed your issues except
> 
> > If all files are deleted a randomization is needed.
> 
> Because I don't understand what you mean?
I mean if a superadmin deletes all information about a person that person disappears but you also have to re-randomize all the people. Might be the correct thing to do.

**Comment by Nautman** [comment]
I think it's only reasonable that they should have to re-randomize manually @Zigolox. Otherwise they might wonder why they were removed. I also don't see this is a very common case for us to hard-code a solution.

**Comment by Zigolox** [comment]
Little bit more space between files and email 
image

**Comment by Zigolox** [comment]
Looks good now. Will merge!

**Review by Zigolox — APPROVED** [review]

**Pull request merged**
