### PR TITLE
Error handler for uploading non PDF

### PR DESCRIPTION
**Pull request by Nautman**

### CODE REVIEW

**Comment by Nautman** [comment]
Can you please test this? I have problems doing so.

**Comment by Nautman** [comment]
Can you please test this? @Zigolox

**Comment by Zigolox** [comment]
This is the current message when uploading a file correctly 
image.
The error message is now correct but not translated to English. 
image

**Comment by Nautman** [comment]
Are you sure? It looks like this for me:
image

The error image is correct though, isn't it?

**Comment by Nautman** [comment]
Nevermind, I can reproduce this. I am working on a fix.

**Comment by Nautman** [comment]
The bug should now be fixed.

**Comment by Zigolox** [comment]
When right error message for 415 gets fixed i will merge this.
image

**Review by Zigolox — APPROVED** [review]

**Comment by Nautman** [comment]
Added 415 error code @Zigolox.

**Comment by Zigolox** [comment]
Not translated otherwise good!
image

**Comment by Nautman** [comment]
It is translated but it requires that you had the language you want selected before you get the error.

**Pull request merged**
